### ISSUE TITLE
division by 0 error

### ISSUE THREAD

**Issue by RyukAD** [thangvubk/FEQE#11]
Hi, Im running the test command

python3 test.py --dataset B100

and it gives the following error :

Traceback (most recent call last):
  File "test.py", line 108, in <module>
    main()
  File "test.py", line 104, in main
    print('Average PSNR: %.4f' %(psnr_avr/len(hr_paths)))
ZeroDivisionError: division by zero

any help would be appreciated

**Comment by RyukAD** [comment]
Also all the images get blurry after your model does its thing. Enhancement?

**Comment by mimikyudesu** [comment]
> Also all the images get blurry after your model does its thing. Enhancement?

Hi, I'm also running this code, and have this problem
I found a small bug in the test.py
At line 94 of test.py 
[sr] = sess.run([t_sr], {t_lr: lr, t_hr: hr})
it set t_lr as the image which downsampling with hr, that make the result of FEQE would be more blurry than before. 
In addition, there is no need to do vgg during test, which means you don't need t_hr.
You can just change 
[sr] = sess.run([t_sr], {t_lr: lr, t_hr: hr})
to 
[sr] = sess.run([t_sr], {t_lr: hr})
that would output what you want.
Hope this can help you.
